### ISSUE TITLE
cannot inherit from final 'android.support.v4.view.GestureDetectorCompat

### ISSUE THREAD

**Issue by W-quan** [dibakarece/DMPlayer#1]
in  ClickItemTouchListener

**Comment by dibakarece** [comment]
I which Android OS version you are getting this error.Please mention the Os version.Before that please check your support v4 library once.

**Comment by jianghejie** [comment]
this is not about os ,it is adout appcompat version,  your version is too old .

**Comment by W-quan** [comment]
i use the latest version.  build tool: 23.0.3 ;   android 6.0; support library: 23.3.0

**Comment by dibakarece** [comment]
Ok, let me check with those appcompact version

**Comment by tellmeleo** [comment]
I opened the application and found that I could not get the data.

**Comment by leerduo** [comment]
have you solved this? @dibakarece

**Comment by dibakarece** [comment]
Please check this new version.I have changed the App compact version and others libs.

**Comment by mostafamoradi** [comment]
i use the latest version
